./src/test/functional/evaluation-note-attendance-management.e2e.spec.ts
./src/test/functional/schedule-lesson-management.e2e.spec.ts
./src/test/functional/event-calendar-management.e2e.spec.ts
./src/test/functional/user-management.e2e.spec.ts
./src/test/functional/subject-curriculum-management.e2e.spec.ts
./src/test/functional/authentication-authorization-management.e2e.spec.ts
./src/test/integration/facade/evaluation-note-attendance-management/evaluation.facade.integration.spec.ts
./src/test/integration/facade/evaluation-note-attendance-management/note.facade.integration.spec.ts
./src/test/integration/facade/evaluation-note-attendance-management/attendance.facade.integration.spec.ts
./src/test/integration/facade/schedule-lesson-management/lesson.facade.integration.spec.ts
./src/test/integration/facade/schedule-lesson-management/schedule.facade.integration.spec.ts
./src/test/integration/facade/subject-curriculum-management/subject.facade.integration.spec.ts
./src/test/integration/facade/subject-curriculum-management/curriculum.facade.integration.spec.ts
./src/test/integration/facade/event-calendar-management/event.facade.integration.spec.ts
./src/test/integration/facade/authentication-authorization-management/authUser.facade.integration.spec.ts
./src/test/integration/facade/user-management/user-administrator.facade.integration.spec.ts
./src/test/integration/facade/user-management/user-teacher.facade.integration.spec.ts
./src/test/integration/facade/user-management/user-student.facade.integration.spec.ts
./src/test/integration/facade/user-management/user-master.facade.integration.spec.ts
./src/test/integration/facade/user-management/user-worker.facade.integration.spec.ts
./src/main/config/tokenService/token-service.instance.ts
./src/main/setups/evaluation-note-attendance-management/evaluation.setup.ts
./src/main/setups/evaluation-note-attendance-management/attendance.setup.ts
./src/main/setups/evaluation-note-attendance-management/note.setup.ts
./src/main/setups/schedule-lesson-management/schedule.setup.ts
./src/main/setups/schedule-lesson-management/lesson.setup.ts
./src/main/setups/subject-curriculum-management/subject.setup.ts
./src/main/setups/subject-curriculum-management/curriculum.setup.ts
./src/main/setups/event-calendar-management/event.setup.ts
./src/main/setups/authentication-authorization-management/authUser.setup.ts
./src/main/setups/user-management/user-student.setup.ts
./src/main/setups/user-management/user-worker.setup.ts
./src/main/setups/user-management/user-administrator.setup.ts
./src/main/setups/user-management/user-teacher.setup.ts
./src/main/setups/user-management/user-master.setup.ts
./src/main/app.ts
./src/modules/@shared/domain/value-object/id.value-object.ts
./src/modules/@shared/type/types.d.ts
./src/modules/@shared/infraestructure/http/express.adapter.ts
./src/modules/@shared/infraestructure/http/http.interface.ts
./src/modules/@shared/utils/formatting.ts
./src/modules/@shared/utils/validations.ts
./src/modules/@shared/test/value-object/id.value-object.spec.ts
./src/modules/@shared/test/util/validations.spec.ts
./src/modules/@shared/test/middleware/authUser.middleware.spec.ts
./src/modules/@shared/application/usecases/use-case.interface.ts
./src/modules/@shared/application/middleware/authUser.middleware.ts