#################################################
## Variables
#################################################

@baseUrl = http://localhost:3003

@masterEmail = master@teste.com.br
@adminEmail = admin@teste.com.br
@teacherEmail = teacher@teste.com.br
@studentEmail = student@teste.com.br
@workerEmail = worker@teste.com.br

@masterPassword = MasterPass123
@adminPassword = AdminPass123
@teacherPassword = TeacherPass123
@studentPassword = StudentPass123
@workerPassword = WorkerPass123

@cnpj = 35.741.901/0001-58


#################################################
## 1) User Creation Flow (register master)
#################################################

### createMaster
# @name createMaster
# Create the master user (optional; if it already exists, skip)
POST {{baseUrl}}/registerTenant
Content-Type: application/json

{
  "email": "{{masterEmail}}",
  "password": "{{masterPassword}}",
  "role": "master",
  "cnpj": "{{cnpj}}"
}
###
@masterId = {{createMaster.response.body.masterId}}


#################################################
## 2) Master Login Flow
## If you DON'T have masterId yet:
##   2.1) Run loginMasterInit (without masterId) to get body.data.0.id
##   2.2) Run loginMaster (with masterId) to get the token
#################################################

### loginMasterInit
# @name loginMasterInit
# LOGIN without masterId to discover the master's id
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "{{masterEmail}}",
  "password": "{{masterPassword}}",
  "role": "master"
}
###
@masterId = {{loginMasterInit.response.body.data.0.id}}

### loginMaster
# @name loginMaster
# LOGIN with masterId to obtain the master token
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "{{masterEmail}}",
  "password": "{{masterPassword}}",
  "role": "master",
  "masterId": "{{masterId}}"
}
###
@masterToken = Bearer {{loginMaster.response.body.token}}


#################################################
## 3) Register users (with master token)
#################################################

### createAdmin
# @name createAdmin
POST {{baseUrl}}/register
Authorization: {{masterToken}}
Content-Type: application/json

{
  "email": "{{adminEmail}}",
  "password": "{{adminPassword}}",
  "role": "administrator",
  "masterId": "{{masterId}}"
}

### createTeacher
# @name createTeacher
POST {{baseUrl}}/register
Authorization: {{masterToken}}
Content-Type: application/json

{
  "email": "{{teacherEmail}}",
  "password": "{{teacherPassword}}",
  "role": "teacher",
  "masterId": "{{masterId}}"
}

### createStudent
# @name createStudent
POST {{baseUrl}}/register
Authorization: {{masterToken}}
Content-Type: application/json

{
  "email": "{{studentEmail}}",
  "password": "{{studentPassword}}",
  "role": "student",
  "masterId": "{{masterId}}"
}

### createWorker
# @name createWorker
POST {{baseUrl}}/register
Authorization: {{masterToken}}
Content-Type: application/json

{
  "email": "{{workerEmail}}",
  "password": "{{workerPassword}}",
  "role": "worker",
  "masterId": "{{masterId}}"
}


#################################################
## 4) Login Flow for other roles (requires masterId)
## Same pattern as master: *Init -> capture body.data.0.id -> Login
#################################################

### loginAdminInit
# @name loginAdminInit
# Discover admin's masterId (without sending masterId)
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "{{adminEmail}}",
  "password": "{{adminPassword}}",
  "role": "administrator"
}
###
@adminMasterId = {{loginAdminInit.response.body.data.0.id}}

### loginAdmin
# @name loginAdmin
# Admin login (with masterId) to get the token
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "{{adminEmail}}",
  "password": "{{adminPassword}}",
  "role": "administrator",
  "masterId": "{{adminMasterId}}"
}
###
@adminToken = Bearer {{loginAdmin.response.body.token}}


### loginTeacherInit
# @name loginTeacherInit
# Discover teacher's masterId
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "{{teacherEmail}}",
  "password": "{{teacherPassword}}",
  "role": "teacher"
}
###
@teacherMasterId = {{loginTeacherInit.response.body.data.0.id}}

### loginTeacher
# @name loginTeacher
# Teacher login (with masterId)
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "{{teacherEmail}}",
  "password": "{{teacherPassword}}",
  "role": "teacher",
  "masterId": "{{teacherMasterId}}"
}
###
@teacherToken = Bearer {{loginTeacher.response.body.token}}


### loginStudentInit
# @name loginStudentInit
# Discover student's masterId
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "{{studentEmail}}",
  "password": "{{studentPassword}}",
  "role": "student"
}
###
@studentMasterId = {{loginStudentInit.response.body.data.0.id}}

### loginStudent
# @name loginStudent
# Student login (with masterId)
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "{{studentEmail}}",
  "password": "{{studentPassword}}",
  "role": "student",
  "masterId": "{{studentMasterId}}"
}
###
@studentToken = Bearer {{loginStudent.response.body.token}}


### loginWorkerInit
# @name loginWorkerInit
# Discover worker's masterId
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "{{workerEmail}}",
  "password": "{{workerPassword}}",
  "role": "worker"
}
###
@workerMasterId = {{loginWorkerInit.response.body.data.0.id}}

### loginWorker
# @name loginWorker
# Worker login (with masterId)
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "{{workerEmail}}",
  "password": "{{workerPassword}}",
  "role": "worker",
  "masterId": "{{workerMasterId}}"
}
###
@workerToken = Bearer {{loginWorker.response.body.token}}


#################################################
## 5) Update Flow (PATCH /authUser)
#################################################

### updateUserPassword
# @name updateUserPassword
# Administrator updates own password
PATCH {{baseUrl}}/authUser
Content-Type: application/json
Authorization: {{adminToken}}

{
  "email": "{{adminEmail}}",
  "authUserDataToUpdate": {
    "password": "AdminPass1234"
  }
}

### updateUserRole
# @name updateUserRole
# Administrator changes own role to teacher
PATCH {{baseUrl}}/authUser
Content-Type: application/json
Authorization: {{adminToken}}

{
  "email": "{{adminEmail}}",
  "authUserDataToUpdate": {
    "role": "teacher"
  }
}

### updateUserEmail
# @name updateUserEmail
# Student updates worker's email (example)
PATCH {{baseUrl}}/authUser
Content-Type: application/json
Authorization: {{studentToken}}

{
  "email": "{{workerEmail}}",
  "authUserDataToUpdate": {
    "email": "worker_updated@teste.com.br"
  }
}


#################################################
## 6) Deletion Flow (DELETE)
#################################################

### deleteUser
# @name deleteUser
# Administrator deletes the teacher user
DELETE {{baseUrl}}/authUser/{{teacherEmail}}
Authorization: {{adminToken}}
