#################################################
## Variables
#################################################

@baseUrl = http://localhost:3003

@masterEmail  = master@teste.com.br
@adminEmail   = admin@teste.com.br
@teacherEmail = teacher@teste.com.br
@studentEmail = student@teste.com.br
@workerEmail  = worker@teste.com.br

@masterPassword  = MasterPass123
@adminPassword   = AdminPass123
@teacherPassword = TeacherPass123
@studentPassword = StudentPass123
@workerPassword  = WorkerPass123

@cnpj = 35.741.901/0001-58

# Sample profile data (adjust as needed)
@firstName = John
@middleName = 
@lastName = Doe
@street = 1st Street
@avenue = Central Ave
@number = 123
@city = Metropolis
@state = SP
@zip = 01000-000
@birthday = 1990-01-15
@graduation = Business Administration
@academicDegrees = MSc, PhD
@salaryValue = 10000
@salaryCurrency = R$


#################################################
## 1) MASTER login (Init -> get masterId -> Login)
#################################################

### loginMasterInit
# @name loginMasterInit
# Discover masterId (without sending masterId)
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "{{masterEmail}}",
  "password": "{{masterPassword}}",
  "role": "master"
}
###
@masterId = {{loginMasterInit.response.body.data.0.id}}

### loginMaster
# @name loginMaster
# Login with masterId to get token
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "{{masterEmail}}",
  "password": "{{masterPassword}}",
  "role": "master",
  "masterId": "{{masterId}}"
}
###
@masterToken = Bearer {{loginMaster.response.body.token}}


#################################################
## 2) ADMINISTRATOR login (Init -> get masterId -> Login)
#################################################

### loginAdminInit
# @name loginAdminInit
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "{{adminEmail}}",
  "password": "{{adminPassword}}",
  "role": "administrator"
}
###
@adminMasterId = {{loginAdminInit.response.body.data.0.id}}

### loginAdmin
# @name loginAdmin
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "{{adminEmail}}",
  "password": "{{adminPassword}}",
  "role": "administrator",
  "masterId": "{{adminMasterId}}"
}
###
@adminToken = Bearer {{loginAdmin.response.body.token}}


#################################################
## 3) TEACHER login (Init -> get masterId -> Login)
#################################################

### loginTeacherInit
# @name loginTeacherInit
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "{{teacherEmail}}",
  "password": "{{teacherPassword}}",
  "role": "teacher"
}
###
@teacherMasterId = {{loginTeacherInit.response.body.data.0.id}}

### loginTeacher
# @name loginTeacher
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "{{teacherEmail}}",
  "password": "{{teacherPassword}}",
  "role": "teacher",
  "masterId": "{{teacherMasterId}}"
}
###
@teacherToken = Bearer {{loginTeacher.response.body.token}}


#################################################
## 4) STUDENT login (Init -> get masterId -> Login)
#################################################

### loginStudentInit
# @name loginStudentInit
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "{{studentEmail}}",
  "password": "{{studentPassword}}",
  "role": "student"
}
###
@studentMasterId = {{loginStudentInit.response.body.data.0.id}}

### loginStudent
# @name loginStudent
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "{{studentEmail}}",
  "password": "{{studentPassword}}",
  "role": "student",
  "masterId": "{{studentMasterId}}"
}
###
@studentToken = Bearer {{loginStudent.response.body.token}}


#################################################
## 5) WORKER login (Init -> get masterId -> Login)
#################################################

### loginWorkerInit
# @name loginWorkerInit
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "{{workerEmail}}",
  "password": "{{workerPassword}}",
  "role": "worker"
}
###
@workerMasterId = {{loginWorkerInit.response.body.data.0.id}}

### loginWorker
# @name loginWorker
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "{{workerEmail}}",
  "password": "{{workerPassword}}",
  "role": "worker",
  "masterId": "{{workerMasterId}}"
}
###
@workerToken = Bearer {{loginWorker.response.body.token}}


#################################################
## 6) PROFILE CREATION (uses the SAME email as login)
##    Endpoints:
##      - /user-master
##      - /user-administrator
##      - /user-teacher
##      - /user-student
##      - /user-worker
#################################################

### createMasterProfile
# @name createMasterProfile
# Authorization with master token; email == master login email
POST {{baseUrl}}/user-master
Authorization: {{masterToken}}
Content-Type: application/json

{
  "name": { "firstName": "{{firstName}}", "lastName": "{{lastName}}" },
  "address": {
    "street": "{{street}}",
    "city": "{{city}}",
    "zip": "{{zip}}",
    "number": {{number}},
    "avenue": "{{avenue}}",
    "state": "{{state}}"
  },
  "email": "{{masterEmail}}",
  "birthday": "{{birthday}}",
  "cnpj": "{{cnpj}}"
}
###
# Adjust to your response shape if needed:
@masterProfileId = {{createMasterProfile.response.body.id}}

### createAdministratorProfile
# @name createAdministratorProfile
# Authorization with admin token; email == admin login email
POST {{baseUrl}}/user-administrator
Authorization: {{masterToken}}
Content-Type: application/json

{
  "name": { "firstName": "{{firstName}}", "middleName": "{{middleName}}", "lastName": "{{lastName}}" },
  "address": {
    "street": "{{street}}",
    "city": "{{city}}",
    "zip": "{{zip}}",
    "number": {{number}},
    "avenue": "{{avenue}}",
    "state": "{{state}}"
  },
  "email": "{{adminEmail}}",
  "birthday": "{{birthday}}",
  "salary": { "salary": {{salaryValue}}, "currency": "{{salaryCurrency}}" },
  "graduation": "{{graduation}}"
}
###
@administratorProfileId = {{createAdministratorProfile.response.body.id}}

### createTeacherProfile
# @name createTeacherProfile
# Authorization with teacher token; email == teacher login email
POST {{baseUrl}}/user-teacher
Authorization: {{teacherToken}}
Content-Type: application/json

{
  "name": { "firstName": "{{firstName}}", "middleName": "{{middleName}}", "lastName": "{{lastName}}" },
  "address": {
    "street": "{{street}}",
    "city": "{{city}}",
    "zip": "{{zip}}",
    "number": {{number}},
    "avenue": "{{avenue}}",
    "state": "{{state}}"
  },
  "email": "{{teacherEmail}}",
  "birthday": "{{birthday}}",
  "salary": { "salary": {{salaryValue}}, "currency": "{{salaryCurrency}}" },
  "graduation": "{{graduation}}",
  "academicDegrees": "{{academicDegrees}}"
}
###
@teacherProfileId = {{createTeacherProfile.response.body.id}}

### createStudentProfile
# @name createStudentProfile
# Authorization with student token; email == student login email
POST {{baseUrl}}/user-student
Authorization: {{studentToken}}
Content-Type: application/json

{
  "name": { "firstName": "{{firstName}}", "middleName": "{{middleName}}", "lastName": "{{lastName}}" },
  "address": {
    "street": "{{street}}",
    "city": "{{city}}",
    "zip": "{{zip}}",
    "number": {{number}},
    "avenue": "{{avenue}}",
    "state": "{{state}}"
  },
  "email": "{{studentEmail}}",
  "birthday": "{{birthday}}",
  "paymentYear": 2025
}
###
@studentProfileId = {{createStudentProfile.response.body.id}}

### createWorkerProfile
# @name createWorkerProfile
# Authorization with worker token; email == worker login email
POST {{baseUrl}}/user-worker
Authorization: {{workerToken}}
Content-Type: application/json

{
  "name": { "firstName": "{{firstName}}", "middleName": "{{middleName}}", "lastName": "{{lastName}}" },
  "address": {
    "street": "{{street}}",
    "city": "{{city}}",
    "zip": "{{zip}}",
    "number": {{number}},
    "avenue": "{{avenue}}",
    "state": "{{state}}"
  },
  "email": "{{workerEmail}}",
  "birthday": "{{birthday}}",
  "salary": { "salary": {{salaryValue}}, "currency": "{{salaryCurrency}}" }
}
###
@workerProfileId = {{createWorkerProfile.response.body.id}}


#################################################
## 7) OTHER ENDPOINTS (CRUD per profile)
## Using master token for admin operations; adjust tokens as needed.
#################################################

############ MASTER ############

### listMasterProfiles
GET {{baseUrl}}/user-master
Authorization: {{masterToken}}

### getMasterProfileById
GET {{baseUrl}}/user-master/{{masterProfileId}}
Authorization: {{masterToken}}

### updateMasterProfile
PATCH {{baseUrl}}/user-master/{{masterProfileId}}
Authorization: {{masterToken}}
Content-Type: application/json

{
  "name": { "firstName": "{{firstName}}", "middleName": "{{middleName}}", "lastName": "{{lastName}}" },
  "address": {
    "street": "{{street}}",
    "city": "{{city}}",
    "zip": "{{zip}}",
    "number": {{number}},
    "avenue": "{{avenue}}",
    "state": "{{state}}"
  },
  "email": "{{masterEmail}}",
  "birthday": "{{birthday}}",
  "cnpj": "{{cnpj}}"
}

### deleteMasterProfile
DELETE {{baseUrl}}/user-master/{{masterProfileId}}
Authorization: {{masterToken}}


############ ADMINISTRATOR ############

### listAdministratorProfiles
GET {{baseUrl}}/user-administrator
Authorization: {{masterToken}}

### getAdministratorProfileById
GET {{baseUrl}}/user-administrator/{{administratorProfileId}}
Authorization: {{masterToken}}

### updateAdministratorProfile
PATCH {{baseUrl}}/user-administrator/{{administratorProfileId}}
Authorization: {{masterToken}}
Content-Type: application/json

{
  "name": { "firstName": "{{firstName}}", "middleName": "{{middleName}}", "lastName": "{{lastName}}" },
  "address": {
    "street": "{{street}}",
    "city": "{{city}}",
    "zip": "{{zip}}",
    "number": {{number}},
    "avenue": "{{avenue}}",
    "state": "{{state}}"
  },
  "email": "{{adminEmail}}",
  "birthday": "{{birthday}}",
  "salary": { "salary": {{salaryValue}}, "currency": "{{salaryCurrency}}" },
  "graduation": "{{graduation}}"
}

### deleteAdministratorProfile
DELETE {{baseUrl}}/user-administrator/{{administratorProfileId}}
Authorization: {{masterToken}}


############ TEACHER ############

### listTeacherProfiles
GET {{baseUrl}}/user-teacher
Authorization: {{masterToken}}

### getTeacherProfileById
GET {{baseUrl}}/user-teacher/{{teacherProfileId}}
Authorization: {{masterToken}}

### updateTeacherProfile
PATCH {{baseUrl}}/user-teacher/{{teacherProfileId}}
Authorization: {{masterToken}}
Content-Type: application/json

{
  "name": { "firstName": "{{firstName}}", "middleName": "{{middleName}}", "lastName": "{{lastName}}" },
  "address": {
    "street": "{{street}}",
    "city": "{{city}}",
    "zip": "{{zip}}",
    "number": {{number}},
    "avenue": "{{avenue}}",
    "state": "{{state}}"
  },
  "email": "{{teacherEmail}}",
  "birthday": "{{birthday}}",
  "salary": { "salary": {{salaryValue}}, "currency": "{{salaryCurrency}}" },
  "graduation": "{{graduation}}",
  "academicDegrees": "{{academicDegrees}}"
}

### deleteTeacherProfile
DELETE {{baseUrl}}/user-teacher/{{teacherProfileId}}
Authorization: {{masterToken}}


############ STUDENT ############

### listStudentProfiles
GET {{baseUrl}}/user-student
Authorization: {{masterToken}}

### getStudentProfileById
GET {{baseUrl}}/user-student/{{studentProfileId}}
Authorization: {{masterToken}}

### updateStudentProfile
PATCH {{baseUrl}}/user-student/{{studentProfileId}}
Authorization: {{masterToken}}
Content-Type: application/json

{
  "name": { "firstName": "{{firstName}}", "middleName": "{{middleName}}", "lastName": "{{lastName}}" },
  "address": {
    "street": "{{street}}",
    "city": "{{city}}",
    "zip": "{{zip}}",
    "number": {{number}},
    "avenue": "{{avenue}}",
    "state": "{{state}}"
  },
  "email": "{{studentEmail}}",
  "birthday": "{{birthday}}",
  "paymentYear": 2025
}

### deleteStudentProfile
DELETE {{baseUrl}}/user-student/{{studentProfileId}}
Authorization: {{masterToken}}


############ WORKER ############

### listWorkerProfiles
GET {{baseUrl}}/user-worker
Authorization: {{masterToken}}

### getWorkerProfileById
GET {{baseUrl}}/user-worker/{{workerProfileId}}
Authorization: {{masterToken}}

### updateWorkerProfile
PATCH {{baseUrl}}/user-worker/{{workerProfileId}}
Authorization: {{masterToken}}
Content-Type: application/json

{
  "name": { "firstName": "{{firstName}}", "middleName": "{{middleName}}", "lastName": "{{lastName}}" },
  "address": {
    "street": "{{street}}",
    "city": "{{city}}",
    "zip": "{{zip}}",
    "number": {{number}},
    "avenue": "{{avenue}}",
    "state": "{{state}}"
  },
  "email": "{{workerEmail}}",
  "birthday": "{{birthday}}",
  "salary": { "salary": {{salaryValue}}, "currency": "{{salaryCurrency}}" }
}

### deleteWorkerProfile
DELETE {{baseUrl}}/user-worker/{{workerProfileId}}
Authorization: {{masterToken}}
